export const operators = [
  { value: 2, name: "רכבת ישראל" },
  { value: 3, name: "אגד" },
  { value: 4, name: "אגד תעבורה" },
  { value: 5, name: "דן" },
  { value: 6, name: "ש.א.מ" },
  { value: 7, name: "נסיעות ותיירות" },
  { value: 8, name: "גי.בי.טורס" },
  { value: 10, name: "מועצה אזורית אילות" },
  { value: 14, name: "נתיב אקספרס" },
  { value: 15, name: "מטרופולין" },
  { value: 16, name: "סופרבוס" },
  { value: 18, name: "קווים" },
  { value: 20, name: "כרמלית" },
  { value: 21, name: "סיטי פס" },
  { value: 23, name: "גלים" },
  { value: 24, name: "מועצה אזורית גולן" },
  { value: 25, name: "אפיקים" },
  { value: 30, name: "דן צפון" },
  { value: 31, name: "דן בדרום" },
  { value: 32, name: "דן באר שבע" },
  { value: 42, name: "ירושלים-רמאללה איחוד" },
  { value: 44, name: "ירושלים-אבו-תור-ענאתא איחוד" },
  { value: 45, name: "ירושלים-אלווסט איחוד" },
  { value: 47, name: "ירושלים-הר הזיתים" },
  { value: 49, name: "ירושלים - עיסאוויה מחנה שעפאט איחוד" },
  { value: 50, name: "ירושלים-דרום איחוד" },
  { value: 51, name: "ירושלים-צור באהר איחוד" },
  { value: 91, name: "מוניות מטרו קו" },
  { value: 92, name: "מוניות שי-לי" },
  { value: 93, name: "מוניות מאיה יצחק שדה" },
  { value: 94, name: "מוניות שירן נסיעות " },
  { value: 95, name: "מוניות יהלום תחבורה" },
  { value: 96, name: "מוניות גלים" },
  { value: 97, name: "אודליה מוניות בעמ" },
  { value: 98, name: "מוניות רב קווית 4-5" },
  { value: 130, name: "מוניות הדר לוד" },
];
